print('Введите расстояние между рядами "a"')
a = int(input())
print('Вееведите расстояние между дырочкаи"b"')
b = int(input())
print('Ввекдите длину свободного края шнурка"l"')
l = int(input())
print('Введите количество дырочек"N"')
N = int(input())
def shnur(a, b, l, N):
  return(2 * l + (2 * N - 1) * a + 2 * (N - 1) * b)
print('Длина шнурка составляет:', shnur(a, b, l, N))